name: Build

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - 'packages/**'

permissions:
  contents: read   # Required to checkout repository
  actions: write   # Required to upload artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0  # Fetch full history for proper versioning

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Calculate recipes to build (pull_request)
        if: github.event_name == 'pull_request'
        id: calculate_recipes_pr
        env:
          GITHUB_EVENT_PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          export CHANGED_RECIPES=$(python ./tools/calc_diff.py \
            --base origin/${GITHUB_EVENT_PULL_REQUEST_BASE_REF} \
            --target ${{ github.sha }})

          echo "Changed recipes: $CHANGED_RECIPES"
          echo "recipes=${CHANGED_RECIPES}" >> $GITHUB_OUTPUT
      
      - name: Build packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pyodide build-recipes "${{ steps.calculate_recipes_pr.outputs.recipes || '*' }}"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        if: always()
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            releases/
          retention-days: 7